[project]
name = "steernav" # workspace root
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "moge",
    "tqdm",
    "numpy<2",
    "transformers==4.49", # required for florence2
    "scipy-stubs",
    "custom_utils",
    "scipy",
    "timm",
    "einops",
]

[tool.setuptools.packages.find]
where = ["src"] # Tells setuptools where to find steernav source code

[tool.uv.sources]
moge = { workspace = true }
custom_utils = { workspace = true }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "astral-cu128"
url = "https://wheels.astral.sh/simple/cu128/"
explicit = true


[tool.uv.workspace]
members = ["services/*"]
#exclude = ["services/venv"]


