[project]
name = "steernav" # workspace root
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flash-attn",
    "OnlineVideoDepthAnything",
    "moge",
    "tqdm>=4.70.0",
    "ipykernel>=7.3.0",
    "transformers>=5.15.0",
    "scipy-stubs~=1.17.1",
    "custom_utils",
    "scipy>=1.17.1",
]

[tool.setuptools.packages.find]
where = ["src"] # Tells setuptools where to find steernav source code

[tool.uv.sources]
OnlineVideoDepthAnything = { workspace = true }
moge = { workspace = true }
custom_utils = { workspace = true }
flash-attn = { index = "astral-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "astral-cu128"
url = "https://wheels.astral.sh/simple/cu128/"
explicit = true


[tool.uv.workspace]
members = ["services/*"]
#exclude = ["services/venv"]


